# Generated by Django 4.2.5 on 2023-10-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_book_author_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['status']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='summery',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookstore.profile'),
        ),
    ]
